const services = [
  {
    slug: 'bms-supply-installation-testing-commissioning',
    title: 'BMS Supply, Installation, Testing & Commissioning',
    shortTitle: 'Supply, Installation, Testing & Commissioning',
    icon: '/images/png/icons/services.png',
    summary: 'Complete BMS delivery under one contract — design review, panel fabrication, field device supply, installation supervision, point-to-point testing, functional performance testing and documented handover.',
    metaTitle: 'BMS Installation & Commissioning | SITC Contractor | SD IoTecs',
    metaDescription: 'End-to-end BMS supply, installation, testing and commissioning on Tridium Niagara, LOYTEC and EasyIO. Panel fabrication to documented handover. Hyderabad, Bengaluru, Pune.',
    intro: 'One contract, one accountable party, from the panel schedule to the signed commissioning record. We take responsibility for the whole delivery — procurement, fabrication, installation supervision, testing and handover — so you are not coordinating four vendors and arbitrating between them when something does not work.',
    scope: [
      "Design review and constructability check against the consultant's specification and control schematics",
      'Points schedule development, I/O verification and panel schedule preparation',
      'Control panel design and fabrication, including power distribution, protection and cable management',
      'Supply of controllers, field devices, sensors, actuators and network infrastructure',
      'Installation supervision and site coordination with MEP, electrical and civil contractors',
      'Controller programming and graphics development on Tridium Niagara, LOYTEC or EasyIO',
      'Point-to-point testing with signed records for every physical and virtual point',
      'Functional performance testing against the specified sequences of operation',
      'Integration of third-party systems over BACnet, Modbus and LonWorks',
      'Operator training and documented handover — as-builts, backups, licences, credentials and O&M manuals',
      'Defects liability support and post-handover optimisation',
    ],
    technical: 'Tridium Niagara 4 for open, multi-vendor supervisory integration where the estate has mixed systems or a long expected life. LOYTEC where deterministic BACnet and LonWorks performance, structured room automation or high-quality touch interfaces are the priority. EasyIO where cost-efficient field-level control is required. We will tell you honestly which is right for your building, including when the answer is none of them.',
    faq: [
      ['Do you work as a main BMS contractor or as a subcontractor to the MEP contractor?', 'We work in either arrangement. Our scope and responsibility are defined clearly at the start so interfaces with MEP, electrical and civil contractors are documented.'],
      ['Can you take over and complete a partially installed system from another contractor?', 'Yes. We begin with a condition survey, verify the installed hardware and points, document gaps, and agree a recovery plan before completing the programming and commissioning.'],
      ['What exactly is handed over at project close?', 'The handover includes signed test records, as-built documentation, controller backups, graphics, licences, credentials, O&M manuals and operator training records.'],
      ['Do you supply and commission in cleanroom and GMP environments?', 'Yes. We plan access, testing evidence and documentation around the site quality process and the environmental requirements of cleanroom and GMP projects.'],
      ['Which cities do you deliver in, and how is site support handled outside them?', 'We regularly deliver in Pune, Mumbai, Hyderabad and Bengaluru, and support projects elsewhere in India through planned site visits and remote engineering support.'],
    ],
  },
  {
    slug: 'continuous-commissioning',
    title: 'Continuous Commissioning',
    shortTitle: 'Continuous Commissioning',
    icon: '/images/png/icons/commissioning.png',
    summary: 'Commissioning is not a signature at handover. We tune sequences and control loops against live operating data, so performance holds in year three as well as week one.',
    metaTitle: 'Continuous Commissioning & Retro-Cx | ASHRAE Guideline 36 | SD IoTecs',
    metaDescription: 'Continuous commissioning and retro-commissioning for BMS estates, including ASHRAE Guideline 36 sequence review, PID tuning, performance monitoring and M&V reporting.',
    intro: 'Buildings drift as occupancy, equipment and operating priorities change. Our continuous commissioning service turns live BMS data into a repeatable programme of review, tuning and verification so comfort, energy performance and compliance do not depend on a one-time handover.',
    scope: [
      'Sequence-of-operation review and rewrite to ASHRAE Guideline 36',
      'Control loop and PID tuning against live trend data',
      'Retro-commissioning of existing estates',
      'Functional performance testing',
      'Ongoing performance monitoring and drift detection',
      'Measurement and verification reporting',
      'Third-party commissioning audits',
    ],
    technical: 'We work with the live data available from Niagara, LOYTEC, EasyIO and mixed-vendor BMS estates. Trend setup, fault review and tuning recommendations are documented so the facilities team can see what changed, why it changed and whether the expected result was achieved.',
    faq: [
      ['How is continuous commissioning different from commissioning at handover?', 'Handover commissioning proves the installed system at one point in time. Continuous commissioning revisits sequences and performance as the building, equipment and operating conditions change.'],
      ['Can you work with an existing BMS installed by another contractor?', 'Yes. We review the existing sequences, trends, alarms and point reliability before proposing a prioritised commissioning plan.'],
      ['Do you use ASHRAE Guideline 36 on every project?', 'We use it where its sequences suit the building and equipment. Where they do not, we adapt the review method to the project requirements and document the engineering basis.'],
    ],
  },
  {
    slug: 'data-modelling-semantic-tagging',
    title: 'Data Modelling & Semantic Tagging',
    shortTitle: 'Data Modelling & Semantic Tagging',
    icon: '/images/png/icons/data-stream.png',
    summary: 'Project Haystack, Brick Schema, Google Digital Buildings and UDMI. We model your estate so analytics and fault detection work on day one, not after a data clean-up nobody budgeted for.',
    metaTitle: 'Haystack, Brick & UDMI Data Modelling for Buildings | SD IoTecs',
    metaDescription: 'Building data modelling and semantic tagging using Project Haystack, Brick Schema, Google Digital Buildings and UDMI for analytics-ready BMS estates.',
    intro: 'A connected building is only useful when its data has meaning. We create governed, documented semantic models that let analytics, fault detection, dashboards and cloud applications work across equipment and sites without relying on one engineer’s memory.',
    scope: [
      'Point inventory and normalisation',
      'Tagging to Project Haystack, Brick Schema or Google Digital Buildings',
      'UDMI device onboarding and payload validation',
      'Naming convention design and governance',
      'Model documentation and handover',
      'Remediation of existing mis-tagged estates',
    ],
    technical: 'Our engineers work across Niagara, LOYTEC, EasyIO and mixed BACnet estates. We map physical points to a consistent model, preserve the source-system context, and provide validation outputs that can be consumed by cloud, analytics and reporting teams.',
    faq: [
      ['Which semantic standard should a building owner choose?', 'The right standard depends on the target applications, existing systems and governance needs. We help select and apply Haystack, Brick, Google Digital Buildings or UDMI rather than forcing one model onto every estate.'],
      ['Can you remediate a building that is already tagged inconsistently?', 'Yes. We inventory the existing points, identify conflicts and missing relationships, then produce a controlled remediation plan with validation evidence.'],
      ['Will the model be usable by our cloud and analytics teams?', 'Yes. The handover includes model documentation, naming rules and validation outputs so downstream teams can use the data without reverse-engineering the BMS.'],
    ],
  },
  {
    slug: 'cloud-iot-integration',
    title: 'Cloud & IoT Integration',
    shortTitle: 'Cloud & IoT Integration',
    icon: '/images/png/icons/cloud-service.png',
    summary: 'Secure telemetry from on-premise BMS to Google Cloud, Azure and AWS using MQTT v5, REST APIs and store-and-forward edge gateways. We integrate into your cloud, on your terms.',
    metaTitle: 'BMS to Cloud Integration | GCP, Azure, AWS, MQTT v5 | SD IoTecs',
    metaDescription: 'Secure BMS to cloud integration for GCP, Azure and AWS using MQTT v5, REST APIs, edge gateways, store-and-forward buffering and OT security practices.',
    intro: 'We connect building systems to the cloud without losing control of the operational technology boundary. The result is reliable, observable telemetry and a documented integration that your IT, facilities and data teams can operate together.',
    scope: [
      'Edge gateway design and deployment',
      'MQTT v5 publishing with store-and-forward buffering',
      'TLS, certificate and credential management',
      'REST API development and consumption',
      'Historian and time-series database integration',
      'Network segmentation and OT security considerations',
    ],
    technical: 'We integrate with Google Cloud, Microsoft Azure and AWS, using MQTT v5, REST APIs and edge patterns suited to the site network. Designs cover identity, certificates, buffering, observability and failure recovery so the cloud connection is dependable rather than merely connected.',
    faq: [
      ['Can you connect a legacy BMS to the cloud?', 'Usually. We first assess the available protocols, gateway options, network constraints and point quality, then choose an integration pattern that does not require replacing a working control system.'],
      ['How do you protect operational technology networks?', 'We use documented network boundaries, least-privilege credentials, certificate management and controlled outbound paths, aligned with the client IT and OT security requirements.'],
      ['What happens when the site loses internet connectivity?', 'Where required, the edge gateway buffers data locally and forwards it after the connection returns, with the retention and recovery behavior agreed during design.'],
    ],
  },
  {
    slug: 'dashboards-and-reporting',
    title: 'Dashboards & Reporting',
    shortTitle: 'Dashboards & Reporting',
    icon: '/images/png/icons/dashboard.png',
    summary: 'Cleanroom and regulated-environment reporting in PDF, Excel and CSV, plus operational dashboards on open-source platforms. No per-seat licence for the reporting layer.',
    metaTitle: 'BMS Dashboards & Cleanroom Reporting | Open Source | SD IoTecs',
    metaDescription: 'BMS dashboards and cleanroom reporting on open-source platforms, with energy, EPI, alarm and compliance reports in PDF, Excel and CSV.',
    intro: 'We turn BMS data into views that operators can act on and records that auditors can trust. Dashboards are designed for daily decisions, while scheduled reports preserve the evidence needed for energy, cleanroom and regulated operations.',
    scope: [
      'Operational dashboards on open-source platforms',
      'Energy performance and EPI reporting',
      'Cleanroom and GMP environmental reporting in PDF, Excel and CSV',
      'Scheduled and on-demand report generation',
      'Alarm and exception reporting',
      'Audit-ready record formats',
    ],
    technical: 'We connect dashboards and reporting to structured BMS and cloud data, using the project semantic model where available. The delivery includes role-appropriate views, time-range and filter behavior, report schedules and a documented data lineage from source point to published result.',
    faq: [
      ['Can reports be generated in the formats our auditors require?', 'Yes. We can produce PDF, Excel and CSV outputs with agreed fields, timestamps, signatures or review information, and retention conventions.'],
      ['Do you need to replace our existing BMS to build dashboards?', 'No. We can use existing BMS protocols, historians or cloud integrations, subject to point quality and access available at the site.'],
      ['Can different users see different dashboard views?', 'Yes. Dashboard layouts and access can be structured around operator, engineering, management and audit use cases.'],
    ],
  },
  {
    slug: '3d-graphics-visualisation',
    title: '3D Graphics & Visualisation',
    shortTitle: '3D Graphics & Visualisation',
    icon: '/images/png/icons/bar-chart.png',
    summary: 'Photoreal plant rooms, isometric layouts and equipment libraries for Niagara, IQ Vision and web front ends, produced by our own studio.',
    metaTitle: '3D BMS Graphics & Plant Room Visualisation | SD IoTecs',
    metaDescription: '3D BMS graphics and plant room visualisation for Niagara, IQ Vision and web front ends, including equipment libraries, animated process graphics and white-label delivery.',
    intro: 'Good graphics make a complex plant understandable at a glance. We create clear, maintainable visualisations that connect equipment, process state and live data for operators, owners and project teams.',
    scope: [
      'Isometric and photoreal plant room graphics',
      'Equipment libraries',
      'Animated process graphics',
      'Niagara Px and IQ Vision graphics packages',
      'Web front-end visualisation',
      'White-label delivery for contractors',
    ],
    technical: 'Our graphics packages can be delivered for Tridium Niagara, IQ Vision and web front ends, with reusable equipment libraries and agreed naming conventions. We can also deliver white-label packages for contractors and integrators.',
    faq: [
      ['Can you build graphics from an existing BMS project?', 'Yes. We use the available points, sequences, drawings and equipment schedules to create a consistent package and identify missing data before production.'],
      ['Do you provide both 2D and 3D graphics?', 'Yes. The mix depends on the operator workflow, platform and project brief, from practical isometric diagrams to photoreal plant-room visualisation.'],
      ['Can another contractor use the graphics package?', 'Yes. We support white-label delivery with agreed file structures, naming and handover requirements. See our specialist visualisation work at ibms3d.com.'],
    ],
    externalLink: {
      label: 'Visit ibms3d.com',
      href: 'https://ibms3d.com',
    },
  },
];

export default services;
